ci: check that bundles branch is not existing (indicates prev pr not merged yet)

diff --git a/.github/workflows/bundles.yaml b/.github/workflows/bundles.yaml
--- a/.github/workflows/bundles.yaml
+++ b/.github/workflows/bundles.yaml
@@ -15,6 +15,13 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Check Bundles Branch Existence
+        run: |
+          if git ls-remote --exit-code --heads origin bundles; then
+            echo "::error::Branch 'bundles' already exists. Delete it before running this workflow"
+            exit 1  
+          fi
+
       - uses: subosito/flutter-action@v2
         with:
           flutter-version: 3.10.0
